'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class dashboard_DD
    
    '''<summary>
    '''ibtnBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtnBack As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lbtest control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtest As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''RepeaterDB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RepeaterDB As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''lbtnNew control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnNew As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lbtnNow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnNow As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''txtMaxCnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaxCnt As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtstartcount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstartcount As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lbtnOld control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbtnOld As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Master property.
    '''</summary>
    '''<remarks>
    '''Auto-generated property.
    '''</remarks>
    Public Shadows ReadOnly Property Master() As ins.MasterPage
        Get
            Return CType(MyBase.Master,ins.MasterPage)
        End Get
    End Property
End Class
